### ISSUE TITLE
ViSU Dataset

### ISSUE THREAD

**Issue by Adeelyousaf** [aimagelab/safe-clip#2]
Hi,

Thank you for your amazing work and for sharing the VISU-Text dataset!

I was wondering if there are any plans to upload the VISU images or dataset generation script as well?

**Comment by tobiapoppi** [comment]
Hi @Adeelyousaf!

Thanks for your interest and appreciation for our work!
Unfortunately, as we declare in our paper, the NSFW visual part of the dataset, due to its explicit nature, is withheld to avoid potential misuse. So we will not release NSFW images.

Despite this, you can find some useful details in the section `reproducibility` of the [HF page of the dataset](https://huggingface.co/datasets/aimagelab/ViSU-Text).
To be more precise, the diffusion model that we used to generate unsafe images is publicly available on HF ([this](https://huggingface.co/stablediffusionapi/newrealityxl-global-nsfw)). The seeds that we used to generate images are also available on our HF dataset page. We used 3 seeds for each prompt to generate NSFW images, and we selected one of the three images which is classified as NSFW from at least on of the two classifiers we used in the paper (Q16 and NudeNet classifier).

If you have any further doubt, feel free to open another issue! 😄 

Tobi
